### ISSUE TITLE
what about block

### ISSUE THREAD

**Issue by mitiger** [dustin/go-coap#35]
can you introduce something about block in coap.  i don't know how to send a big file with this package.
thank you.

**Comment by dubek** [comment]
This was already reported in #26 , so I'm closing this as duplicate.

Currently block-wise CoAP transfers are not implemented in go-coap. We do appreciate code contributions! (hint, hint :-)

**Comment by mitiger** [comment]
oh，  do you hava plan to do this job? we are waiting in joyful hope. 
thanks!!!
