### ISSUE TITLE
How to define Resources or Endpoints on ServerSide?

### ISSUE THREAD

**Issue by uguessmyid** [dustin/go-coap#37]
On Server Side How to define Resources or Endpoints and write handlers in specific to those endpoints using your library?
And also on Client side how to write data to particular endpoint or resource?

Can you write a sample server-client program with Endpoints included.

**Comment by dustin** [comment]
Check out the examples directory.  I've got some updates that should help
make this clearer.

**Comment by uguessmyid** [comment]
Thank you @dustin

**Comment by uguessmyid** [comment]
@dustin can you write a client example which receives messages that are published to particular endpoint on server. (Inshort a Subscriber)
