### ISSUE TITLE
Can anyone help manage the pull requests here?

### ISSUE THREAD

**Issue by dustin** [dustin/go-coap#55]
I've been putting most of my efforts into mqtt lately and haven't spent any time in CoAP.  There appears to be a lot of interest here.  Does anyone want to help push this forward?

**Comment by dubek** [comment]
Unfortunately I'm also not working with CoAP anymore. I'm still managing the crosscoap repo (which depends on go-coap) - I'm mainly merging trivial PRs there just to keep it alive (but don't use it myself).

@besedad maybe you're interested?

**Comment by besedad** [comment]
Yes, I would be interested to maintain go-coap.

**Comment by dustin** [comment]
Thanks!  I'm still quite focused on mqtt and failing to keep up.
